---
### New playbook
- hosts: webservers
  ## if you want to only have specific domains from your `vars.yml` file to be executed then you can use the
  ## `-e` command line flag to send in either the domains to include via a `include_domains` var, or domains to exclude
  ## via a `skip_domains` variable.
  ## Example:
  ## $:> ansible-playbook playbook.yml -e "include_domains=domaina.com,domainb.com,domainc.com"
  vars:
    domuse: "{{ include_domains | default('all') }}"
    domains_to_use: "{{ domuse.split(',') }}"
    domskip: "{{ skip_domains | default('none') }}"
    domains_to_skip: "{{ domskip.split(',') }}"
    post_run_messages: []
  vars_files:
    - vars.yml
  remote_user: "{{ remote_sudo_user }}"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  roles:
    -
     role: common
     tags: [init]
    -
     role: user
     tags: [init, user]
    -
     role: ssh
     tags: [init, ssh]
    -
     role: nginx
     tags: [nginx, web]
    -
     role: nginxsites
     tags: [nginx, web, sites]
    -
     role: php
     tags: [init]
    -
     role: mariadb
     tags: [init]
    -
     role: wp-cli
     tags: [init]
    -
     role: wordpress
     tags: [web, wordpress]
    -
     role: importdb
     tags: [web, wordpress, import]
    -
     role: letsencrypt
     tags: [web, ssl]
    -
     role: gitdeploy
     tags: [deploy]
    -
     role: logentries
     tags: [logentries]
    -
     role: geerlingguy.nodejs
     tags: [node]
    -
     role: grunt
     tags: [grunt]
    -
     role: geerlingguy.composer
     tags: [composer]
    -
     role: geerlingguy.redis
     tags: [redis]
    -
     role: php-redis
     tags: [redis]
    -
     role: buildmachine.webhook.listener
     tags: [buildmachine, webhook]
    -
     role: grunt-buildmachine
     tags: [buildmachine, gruntbm]
    -
     role: iptables
     tags: [iptables]
    -
     role: postrun.message
     tags:
      - always